application: montecarlo-integration
version: 1
runtime: python
api_version: 1

builtins:
- appstats: on
- datastore_admin: on

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.jar$

handlers:

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/deferred.py
  login: admin

- url: /(.*\.(js))
  static_files: js/\1
  upload: js/(.*\.(js))
  expiration: 5h

- url: /css
  static_dir: css

- url: /(.*\.(gif|jpg|png))
  static_files: images/\1
  upload: images/(.*\.(gif|jpg|png))
  expiration: 5h

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /record
  script: app.py

- url: /chart
  script: app.py

- url: /
  script: app.py
